### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sffr-dev** [NastyaBk/Skill-Factory_landing-page-project#1]
1. https://github.com/NastyaBk/Skill-Factory_landing-page-project/blob/a22c92c941a91a6b407b986d04c5ac030cdbaa93/CSS/style.css#L1-L3 Здесь необходимо прописать `font-family: "Nunito Sans";`
2. https://github.com/NastyaBk/Skill-Factory_landing-page-project/blob/a22c92c941a91a6b407b986d04c5ac030cdbaa93/CSS/style.css#L5 Это селектор элемента с классом `body`. Вам нужно выбрать элемент с тегом `body`
3. https://github.com/NastyaBk/Skill-Factory_landing-page-project/blob/a22c92c941a91a6b407b986d04c5ac030cdbaa93/CSS/style.css#L7 `font-family: 'Nunito Sans', Arial;`
4. https://github.com/NastyaBk/Skill-Factory_landing-page-project/blob/a22c92c941a91a6b407b986d04c5ac030cdbaa93/index.html#L27 А чего кнопка не в контейнере?
5. У пунктов меню должен быть эффект смены цвета при наведении и проверьте размер шрифта
6. Телефон потерялся
7. Сделайте мобильную версию хедера

**Comment by NastyaBk** [comment]
Все пункты, кроме 7 изменила. У меня совсем не выходит сделать выравнивание хэдера, соответсвенно сложно сделать нормальную мобильную версию с таким хэдером..

**Comment by sffr-dev** [comment]
1. Элемента `container` не существует. В п.4 я имел ввиду, что кнопку нужно поместить внутрь https://github.com/NastyaBk/Skill-Factory_landing-page-project/blob/b89d3063148c0af2c6f2f2695ec9361b557ec72d/index.html#L12
2. Уберите у кнопки и телефона маржины и у вас все выровняется
